name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Debug step: Check repository structure
      - name: Debug - List repository contents
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Repository contents:"
          find . -type d -maxdepth 2 | sort

      # Set up Node.js for frontend build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Build frontend
      - name: Build frontend
        run: |
          # Check if frontend directory exists
          if [ ! -d "frontend" ]; then
            echo "Frontend directory not found, creating structure..."
            mkdir -p frontend/src
            # Create basic package.json if it doesn't exist
            if [ ! -f "frontend/package.json" ]; then
              echo '{
                "name": "fastdownloadlk-frontend",
                "version": "1.0.0",
                "scripts": {
                  "build": "mkdir -p dist && cp -r ../public/* dist/ || echo \"No public directory found\""
                }
              }' > frontend/package.json
            fi
          fi
          
          cd frontend
          npm install
          npm run build
        env:
          VITE_API_URL: "https://fastlk.netlify.app/.netlify/functions/server"

      # Verify frontend build
      - name: Verify frontend build
        run: |
          echo "Checking frontend build output:"
          if [ -d "frontend/dist" ]; then
            echo "Frontend dist directory found:"
            ls -la frontend/dist
          else
            echo "WARNING: frontend/dist directory not found!"
            echo "Looking for alternative build outputs:"
            find . -name "dist" -type d
            # Create a minimal dist directory if needed
            mkdir -p frontend/dist
            echo "<html><body><h1>FastDownloadLK</h1><p>Site is under maintenance. Please check back later.</p></body></html>" > frontend/dist/index.html
          fi
      
      # Create deployment directory (without Jekyll)
      - name: Create deployment directory
        run: |
          # Create deploy directory
          mkdir -p deploy
          
          # Create .nojekyll file to disable Jekyll processing
          touch deploy/.nojekyll
          
          # Try to copy frontend build files
          if [ -d "frontend/dist" ] && [ "$(ls -A frontend/dist)" ]; then
            echo "Copying frontend/dist files to deploy directory..."
            cp -r frontend/dist/* deploy/
            
            # Make sure the favicon.svg exists at the root
            if [ -f "frontend/dist/favicon.svg" ] && [ ! -f "deploy/favicon.svg" ]; then
              echo "Copying favicon.svg to deploy root..."
              cp frontend/dist/favicon.svg deploy/
            elif [ ! -f "deploy/favicon.svg" ]; then
              echo "Creating a basic favicon.svg..."
              echo '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 8.5l-5 3a.5.5 0 0 1-.75-.4v-6a.5.5 0 0 1 .75-.4l5 3a.5.5 0 0 1 0 .8z" fill="#0078d7"/></svg>' > deploy/favicon.svg
            fi
          # If frontend/dist is empty or doesn't exist, try public directory
          elif [ -d "public" ]; then
            echo "Using public directory as fallback..."
            cp -r public/* deploy/ || echo "Warning: No files in public directory"
            
            # Create basic favicon.svg if not exists
            if [ ! -f "deploy/favicon.svg" ]; then
              echo "Creating a basic favicon.svg..."
              echo '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 8.5l-5 3a.5.5 0 0 1-.75-.4v-6a.5.5 0 0 1 .75-.4l5 3a.5.5 0 0 1 0 .8z" fill="#0078d7"/></svg>' > deploy/favicon.svg
            fi
          # Last resort: create a basic HTML file
          else
            echo "Creating basic index.html as fallback..."
            echo "<html><body><h1>FastDownloadLK</h1><p>Site is under maintenance. Please check back later.</p></body></html>" > deploy/index.html
            
            # Create basic favicon.svg 
            echo "Creating a basic favicon.svg..."
            echo '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 8.5l-5 3a.5.5 0 0 1-.75-.4v-6a.5.5 0 0 1 .75-.4l5 3a.5.5 0 0 1 0 .8z" fill="#0078d7"/></svg>' > deploy/favicon.svg
          fi
          
          # Show the contents of the deployment directory
          echo "Contents of deploy directory:"
          ls -la deploy/
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
          clean: true 