name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Debug step to show repository structure
      - name: List repository contents
        run: |
          ls -la
          ls -la ./frontend || echo "Frontend directory not found"

      # Create frontend structure if it doesn't exist
      - name: Create frontend structure if needed
        run: |
          if [ ! -d "frontend" ]; then
            echo "Creating minimal frontend structure"
            mkdir -p frontend/dist
            echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>FastDownloadLK</title><style>body{font-family:Arial,sans-serif;margin:0;padding:20px;background-color:#1e293b;color:white;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh}.container{max-width:800px;margin:0 auto}h1{color:#38bdf8}p{line-height:1.6}.button{display:inline-block;background-color:#38bdf8;color:white;padding:10px 20px;border-radius:5px;text-decoration:none;margin-top:20px;font-weight:bold}</style></head><body><div class="container"><h1>FastDownloadLK</h1><p>Video Downloader Service</p><p>The application is being set up. Please check back soon!</p><a href="https://fastlk.netlify.app" class="button">Go to API</a></div></body></html>' > frontend/dist/index.html
            echo "Created minimal frontend"
          else
            echo "Frontend directory exists"
          fi

      # Setup Node.js only if frontend exists and has package.json
      - name: Setup Node.js
        if: hashFiles('frontend/package.json') != ''
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Install and build only if frontend exists and has package.json
      - name: Install Dependencies and Build
        if: hashFiles('frontend/package.json') != ''
        run: |
          cd frontend
          npm install
          npm run build
          ls -la
          ls -la ./dist || echo "Dist directory not found after build"
        env:
          VITE_API_URL: 'https://fastlk.netlify.app'

      - name: Create .nojekyll file
        run: |
          cd frontend/dist
          touch .nojekyll
          if [ -f "index.html" ]; then
            cp index.html 404.html
            echo "Created .nojekyll file and 404.html"
          else
            echo "Warning: index.html not found, could not create 404.html"
          fi

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 