name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Debug step: Check repository structure
      - name: Debug - List repository contents
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Repository contents:"
          find . -type d -maxdepth 2 | sort

      - name: Create deployment directory
        run: |
          # Create a fresh deploy directory
          rm -rf deploy
          mkdir -p deploy
          
          # Copy our HTML files
          cp index.html deploy/
          cp 404.html deploy/
          
          # Create essential GitHub Pages files
          touch deploy/.nojekyll
          
          # Create a blank index.md file to prevent README.md from being used
          echo "" > deploy/index.md
          
          # Ensure README.md doesn't override index.html
          if [ -f "README.md" ]; then
            echo "Renaming README.md to readme.txt to prevent it from being displayed instead of index.html"
            cp README.md deploy/readme.txt
          fi
          
          # Show the contents of the deploy directory
          echo "Contents of deployment directory:"
          ls -la deploy/

      # Deploy to GitHub Pages using JamesIves/github-pages-deploy-action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
          clean: true

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: https://fastlk.netlify.app/api 